baseURL: https://landpagepaulo.netlify.app
languageCode: pt-br
paginate: 6
theme: portio-hugo
title: Imóveis Caixa | PB
menu:
  # main:
    # - name: Home
    #   url: '#home'
    #   weight: 1
    # - name: Quem somos
    #   url: /quem_somos
    #   weight: 1
    # - name: Serviços
    #   url: /servicos
    #   weight: 3
    # - name: Catálogo de imóveis
    #   url: /catalogo
    #   weight: 2
    # - name: Como comprar?
    #   url: /como_comprar
    #   weight: 3
    # - name: Contato
    #   url: /contato
    #   weight: 4
    # - name: Blog
    #   url: '#blog'
    #   weight: 7
    # - name: Contact
    #   url: '#contact'
    #   weight: 8
  # sitemap:
  #   - name: About me
  #     url: about
  #     weight: 1
  #   - name: Frequently Ask Question
  #     url: '#'
  #     weight: 2
  #   - name: Privacy & Policy
  #     url: '#'
  #     weight: 3
  #   - name: Latest Article
  #     url: '#'
  #     weight: 4
params:
  address:
    address: Rua Vidal de Negreiros, 98 - Patos | PB
    email: contato@paulomorais.com
    # openingHours: Open from 10am to 6pm (close at 5pm Sundays)
    phone: (83) 98184 7272
  blogPageURL: blog
  contactLink: /contato
  copyright: All right reserved copyright © QAchado 2020
  fabformURL: https://fabform.io/f/JpTXRUa
  footerLogo: images/contact/logoEdit.png
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.png
  map:
    APIkey: YOUR GOOGLE MAP API
    latitude: '23.7783741'
    longitude: '90.3746808'
    pinImage: images/pin.png
  social:
    - icon: fa-facebook-official
      url: https://www.facebook.com/paulomoraisimoveis/
      weight: 1
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/paulo-morais-a031a4120/
      weight: 2
    - icon: fa-instagram
      url: https://www.instagram.com/paulomoraisimoveis/
      weight: 3
    # - icon: fa-twitter-square
    #   url: https://twitter.com/
    #   weight: 4
